"""empty message

Revision ID: 346f8b97aff4
Revises: 
Create Date: 2020-03-10 11:33:44.527585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '346f8b97aff4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentInfomation',
    sa.Column('Student_ID', sa.String(length=20), nullable=False),
    sa.Column('Student_Name', sa.String(length=20), nullable=False),
    sa.Column('Student_Ph_Num', sa.String(length=20), nullable=False),
    sa.Column('Student_email', sa.String(length=20), nullable=False),
    sa.Column('Student_class', sa.String(length=20), nullable=False),
    sa.Column('Student_password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Student_ID')
    )
    op.create_table('studentResume',
    sa.Column('Student_Name', sa.String(length=20), nullable=False),
    sa.Column('Student_Ph_Num', sa.String(length=20), nullable=False),
    sa.Column('Student_email', sa.String(length=20), nullable=False),
    sa.Column('Student_Edu_experience_address', sa.String(length=50), nullable=False),
    sa.Column('Student_Internship_experience_address', sa.String(length=50), nullable=False),
    sa.Column('Student_Project_experience_address', sa.String(length=50), nullable=False),
    sa.Column('Student_Skills_others_address', sa.String(length=50), nullable=False),
    sa.Column('Student_Personal_summary_address', sa.String(length=50), nullable=False),
    sa.Column('Student_Photo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Student_Name', 'Student_Skills_others_address')
    )
    op.create_table('studentTerm',
    sa.Column('Student_ID', sa.String(length=20), nullable=False),
    sa.Column('Student_Name', sa.String(length=20), nullable=False),
    sa.Column('Student_class', sa.String(length=20), nullable=False),
    sa.Column('Student_Term_information', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Student_ID')
    )
    op.create_table('student_Learn_Plan',
    sa.Column('Student_Learn_Plan01_address', sa.String(length=50), nullable=False),
    sa.Column('Student_Opinion01_address', sa.String(length=50), nullable=True),
    sa.Column('Student_Learn_Plan02_address', sa.String(length=50), nullable=True),
    sa.Column('Student_Opinion02_address', sa.String(length=50), nullable=True),
    sa.Column('Student_Learn_Plan03_address', sa.String(length=50), nullable=True),
    sa.Column('Student_Opinion03_address', sa.String(length=50), nullable=True),
    sa.Column('Student_Learn_Plan04_address', sa.String(length=50), nullable=True),
    sa.Column('Student_Opinion04_address', sa.String(length=50), nullable=True),
    sa.Column('Student_Learn_Plan05_address', sa.String(length=50), nullable=True),
    sa.Column('Student_Opinion05_address', sa.String(length=50), nullable=True),
    sa.Column('Student_Learn_Plan06_address', sa.String(length=50), nullable=True),
    sa.Column('Student_Opinion06_address', sa.String(length=50), nullable=True),
    sa.Column('Student_Learn_Plan07_address', sa.String(length=50), nullable=True),
    sa.Column('Student_Opinion07_address', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Student_Learn_Plan01_address')
    )
    op.create_table('teacherInfomation',
    sa.Column('Teacher_ID', sa.String(length=20), nullable=False),
    sa.Column('Teacher_Name', sa.String(length=20), nullable=False),
    sa.Column('Teacher_Ph_Num', sa.String(length=20), nullable=False),
    sa.Column('Teacher_email', sa.String(length=20), nullable=False),
    sa.Column('Teacher_class', sa.String(length=20), nullable=False),
    sa.Column('Teacher_password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Teacher_ID')
    )
    op.create_table('termNum',
    sa.Column('Student_Term_01', sa.String(length=20), nullable=False),
    sa.Column('Student_Term_02', sa.String(length=20), nullable=False),
    sa.Column('Student_Term_03', sa.String(length=20), nullable=False),
    sa.Column('Student_Term_04', sa.String(length=20), nullable=False),
    sa.Column('Student_Term_05', sa.String(length=20), nullable=False),
    sa.Column('Student_Term_06', sa.String(length=20), nullable=False),
    sa.Column('Student_Term_07', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Student_Term_01')
    )
    op.drop_table('studentinfomation')
    op.drop_table('student_learn_plan')
    op.drop_table('termnum')
    op.drop_table('studentterm')
    op.drop_table('aa')
    op.drop_table('teacherinfomation')
    op.drop_table('studentresume')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentresume',
    sa.Column('Student_Name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_Ph_Num', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_email', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_Edu_experience_address', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Student_Internship_experience_address', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Student_Project_experience_address', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Student_Skills_others_address', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Student_Personal_summary_address', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Student_Photo', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Student_Name', 'Student_Skills_others_address'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('teacherinfomation',
    sa.Column('Teacher_ID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Teacher_Name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Teacher_Ph_Num', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Teacher_email', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Teacher_class', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Teacher_password', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Teacher_ID'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('aa',
    sa.Column('name', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('studentterm',
    sa.Column('Student_ID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_Name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_class', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_Term_information', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Student_ID'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('termnum',
    sa.Column('Student_Term_01', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_Term_02', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_Term_03', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_Term_04', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_Term_05', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_Term_06', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_Term_07', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Student_Term_01'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('student_learn_plan',
    sa.Column('Student_Learn_Plan01_address', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Student_Opinion01_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Student_Learn_Plan02_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Student_Opinion02_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Student_Learn_Plan03_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Student_Opinion03_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Student_Learn_Plan04_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Student_Opinion04_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Student_Learn_Plan05_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Student_Opinion05_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Student_Learn_Plan06_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Student_Opinion06_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Student_Learn_Plan07_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Student_Opinion07_address', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Student_Learn_Plan01_address'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('studentinfomation',
    sa.Column('Student_ID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_Name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_Ph_Num', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_email', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_class', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Student_password', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Student_ID'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('termNum')
    op.drop_table('teacherInfomation')
    op.drop_table('student_Learn_Plan')
    op.drop_table('studentTerm')
    op.drop_table('studentResume')
    op.drop_table('studentInfomation')
    # ### end Alembic commands ###
